### ISSUE TITLE
Projectiles un-randomizing mid run

### ISSUE THREAD

**Issue by Efferrari** [Goorakh/RoR2Mods#4]
As the title says, my friends and I were playing last night and a few stages in, a few of our character abilities had defaulted back to their normal state.

We've played a lot of this mod (30-40hrs) and it seems to be an issue since the update for hitscan projectile randomization.

Next time it happens I'll try and grab a video for you.

**Comment by Goorakh** [comment]
This is a known issue and will be fixed in the next mod update (should be in the next few days). Thank you for reporting :)

**Comment by Goorakh** [comment]
And by "next few days", I apparently meant "right now". This bug is fixed in version 0.7.2.
