### ISSUE TITLE
Engineer Sentries not random despite setting being on

### ISSUE THREAD

**Issue by kirubotu** [Goorakh/RoR2Mods#9]
Just as the title implies, as the recent update, it has broken a few things in the mod. I havent full tested it, but I recommended testing it all around when able. But for the most part, Engineers turrets (lasers or gauss) do not randomise nor do drones in my case.

**Comment by Goorakh** [comment]
Hi, thank you for the report, unfortunately this will not be fixed as nobody is maintaining the project anymore.

I have deprecated the mod on Thunderstore for the time being though, you can still download it with a direct link or use it if you already have a profile with the mod installed. What works will work, and what doesn't, won't be fixed.

Sorry to disappoint 😅
